apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: tasks
      port: 8080
      type: REST
      networkVisibility: Public
      context: /
      schemaFilePath: openapi.yaml
  outbound:
    serviceReferences:
      - name: choreo:///orgpwc/appointment-management/jgtqqk/8b1c3/v1.0/ORGANIZATION
        connectionConfig: 01ef000a-c5cd-1170-bdbb-712638f7a06b
        env:
          - from: ServiceURL
            to: APPOINTMENT_SERVICE_URL
          - from: ConsumerKey
            to: APPOINTMENTS_OAUTH_CLIENT_ID
          - from: ConsumerSecret
            to: APPOINTMENTS_OAUTH_CLIENT_SECRET
          - from: TokenURL
            to: APPOINTMENTS_OAUTH_TOKEN_URL
