openapi: 3.0.0
info:
  title: Tasks Backend API
  description: Backend service for managing tasks.
  version: "1.0"
servers:
  - url: http://localhost:8080
    description: Development server
paths:
  /get_mail:
    get:
      summary: Get unique emails
      description: Retrieves a list of unique email addresses associated with tasks.
      responses:
        '200':
          description: List of unique email addresses
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /get_tasks/{email}:
    get:
      summary: Get tasks by email
      description: Retrieves tasks associated with a specific email address.
      parameters:
        - in: path
          name: email
          required: true
          schema:
            type: string
            format: email
      responses:
        '200':
          description: List of tasks for the given email address
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    task:
                      type: string
                    deadline:
                      type: string
                      format: date
  /get_all_info:
    get:
      summary: Get all task information
      description: Retrieves all task information including email, task, and deadline.
      responses:
        '200':
          description: List of all task information
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    email:
                      type: string
                    task:
                      type: string
                    deadline:
                      type: string
                      format: date
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
