openapi: 3.0.0
info:
  title: Tasks Backend API (Public)
  description: Backend service for managing tasks.
  version: "1.0"
servers:
  - url: http://localhost:8060
    description: Development server
paths:
  /get_tasks/{email}:
    get:
      summary: Get tasks by email
      description: Retrieves tasks associated with a specific email address.
      parameters:
        - in: path
          name: email
          required: true
          schema:
            type: string
            format: email
      responses:
        '200':
          description: List of tasks for the given email address
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    task:
                      type: string
                    deadline:
                      type: string
                      format: date
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
